export const mockPosts = [
  {
    id: 1,
    title: '질서 너머',
    content: '인생의 다음 단계로 나아가는 12가지 법칙',
    nickname: '조던 피터슨',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 1,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/599/x9788901249599.jpg',
    image2: 'http://image.yes24.com/momo/TopCate3356/MidCate007/335564594.jpg',
    image3: 'http://image.yes24.com/momo/TopCate3356/MidCate007/335564723.jpg',
    image4: null,
    image5: null,
    type: 3,
    state: '거래전',
    address: '서울특별시 동작구 사당동',
    roadAddress: '동작대로',
    authorProfileImage: null,
  },
  {
    id: 2,
    title: '달러구트 꿈 백화점',
    content: '주문하신 꿈은 매진입니다',
    nickname: '이미예',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 45,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/909/x9791165341909.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 8,
    state: '거래전',
    address: '서울특별시 성동구 도선동',
    roadAddress: '동작대로',
  },
  {
    id: 3,
    title: '작은 별이지만 빛나고 있어',
    content: '소윤 에세이',
    nickname: '소윤',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 0,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/153/x9791197037153.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 8,
    state: '거래전',
    address: '서울특별시 동작구 사당동',
    roadAddress: '동작대로',
    authorProfileImage: null,
  },
  {
    id: 4,
    title: '마지막 몰입: 나를 넘어서는 힘',
    content: '내 안의 잠재력을 200% 끌어올리는 마인드셋',
    nickname: '짐 퀵',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 1,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/968/x9791162541968.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 8,
    state: '거래전',
    address: '서울특별시 동작구 사당동',
    roadAddress: '동작대로',
    authorProfileImage: null,
  },
  {
    id: 5,
    title: '아몬드(양장본 HardCover)',
    content: '손원평 장편소설',
    nickname: '손원평',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 1,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/267/x9788936434267.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 8,
    state: '거래전',
    address: '서울특별시 강남구 역삼동',
    roadAddress: '동작대로',
  },
  {
    id: 6,
    title: '공정하다는 착각',
    content: '능력주의는 모두에게 같은 기회를 제공하는가',
    nickname: '마이클 샌델',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 8,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/452/x9791164136452.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 3,
    state: '거래전',
    address: '서울특별시 동작구 사당동',
    roadAddress: '동작대로',
    authorProfileImage: null,
  },
  {
    id: 7,
    title: '위대한 시크릿(양장본 HardCover)',
    content: '능력주의는 모두에게 같은 기회를 제공하는가',
    nickname: '론다 번',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 1,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/995/x9788925588995.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 3,
    state: '거래전',
    address: '서울특별시 강남구 역삼동',
    roadAddress: '동작대로',
    authorProfileImage: null,
  },
  {
    id: 8,
    title: '끌리는 말투 호감 가는 말투',
    content: '어떤 상황에서든 원하는 것을 얻는 말하기 법칙',
    nickname: '리우난',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 4,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/481/x9788972773481.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 3,
    state: '거래전',
    address: '서울특별시 동작구 사당동',
    roadAddress: '동작대로',
    authorProfileImage: null,
  },
  {
    id: 9,
    title: '어떻게 말해줘야 할까',
    content:
      '오은영의 현실밀착 육아회화 | 버럭하지 않고 분명하게 알려주는 방법',
    nickname: '오은영',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 11,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/652/x9788934986652.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 3,
    state: '거래전',
    address: '서울특별시 동작구 사당동',
    roadAddress: '동작대로',
    authorProfileImage: null,
  },
  {
    id: 10,
    title: '싱크 어게인',
    content: '모르는 것을 아는 힘',
    nickname: '애덤 그랜트',
    createdAt: '2021-05-17 15:14:37',
    interest_cnt: 5,
    image1:
      'http://image.kyobobook.co.kr/images/book/xlarge/079/x9788947547079.jpg',
    image2: null,
    image3: null,
    image4: null,
    image5: null,
    type: 3,
    state: '거래전',
    address: '서울특별시 동작구 사당동',
    roadAddress: '동작대로',
    authorProfileImage: null,
  },
];
